name: photo_uploader
description: Flutter Photo Uploader is a Flutter package which uses the Camera package to take a picture, crop it, and post the data to an endpoint.
version: 0.1.0
author: Alex Rindone
homepage: https://nubeer.io

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  camera: ^0.5.8+5
  http: ^0.12.1
  flutter:
    sdk: flutter

dev_dependencies:
  path_provider: ^0.5.0
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
